export const TOGGLE_DRAWER = "TOGGLE_DRAWER";
export const CHANGE_OPENED = "CHANGE_OPENED";
export const TOGGLE_NOTIFICATION = "TOGGLE_NOTIFICATION";
export const TOGGLE_THEME = "TOGGLE_THEME";
export const TOGGLE_DIRECTION = "TOGGLE_DIRECTION";
export const TOGGLE_SPEED_DIAL = "TOGGLE_SPEED_DIAL";